from prepare_shake import *
print("Preparing mango shake")
mangoShakePreparation = MangoShakePreparation()
mangoShakePreparation.prepare()
print("Preparing pineapple shake")
pineappleShakePreparation = PineappleShakePreparation()
pineappleShakePreparation.prepare()
print("Preparing detox shake")
detoxShakePreparation = DetoxShakePreparation()
detoxShakePreparation.prepare()
